import {
  alwaysPickDefault,
  ParseFailure,
  ParserInput,
  PickRequest,
} from "../picks.ts";

import {
  NOT_FOUND,
  runWithPicks,
  Solution,
  SpanPicker,
  walkAllPaths,
} from "../solver.ts";

import { Success } from "../results.ts";

class PickFailed extends Error {
  private constructor(msg: string) {
    super(msg);
  }
  static create(req: Arbitrary<unknown>, tries: number): PickFailed {
    return new PickFailed(`Failed to generate ${req} after ${tries} tries`);
  }
}

/**
 * A function that can pick values from integer ranges or arbitraries.
 *
 * @throws PickFailed if a value couldn't be generated due to running out of
 * retries.
 */
export interface PickFunction {
  (req: PickRequest): number;
  <T>(req: Arbitrary<T>): T;
}

/**
 * Creates a PickFunction that can handle backtracking.
 * @param picker a source of picks and an output for spans.
 * @param maxTries how many times to try to generate a pick from each Arbitrary.
 * (Set it to 1 to disable backtracking.)
 */
export function makePickFunction(
  picker: SpanPicker,
  maxTries: number,
): PickFunction {
  if (!picker) throw new Error("no integer source given");
  if (maxTries < 1 || !Number.isSafeInteger(maxTries)) {
    throw new Error("maxTries must be a positive integer");
  }

  const doPick: PickFunction = <T>(
    req: PickRequest | Arbitrary<T>,
  ): number | T => {
    if (req instanceof PickRequest) {
      return picker.pick(req);
    }
    for (let tries = 0; tries < maxTries; tries++) {
      const level = picker.startSpan();
      const val = req.callback(doPick);
      if (val !== NOT_FOUND) {
        picker.endSpan(level);
        return val;
      }
      if (tries < maxTries - 1) {
        // Cancel only when we're not out of tries.
        picker.cancelSpan(level);
      }
    }
    // Give up. This is normal when backtracking is turned off.
    // Don't cancel so that the picks used in the failed run are available
    // to the caller.
    throw PickFailed.create(req, maxTries);
  };

  return doPick;
}

/**
 * A function that attempts to generate one of the values of an Arbitrary, given
 * some picks.
 *
 * The function may return {@link NOT_FOUND} as a way of backtracking if it's given
 * some picks that can't be used. When that happens, the caller should try again
 * with different picks.
 *
 * (This is a better way than a loop to implement backtracking because the
 * caller can forget about the picks that led to a dead end.)
 *
 * The *default value* of a parser is whatever it returns when its input is all
 * default values. Returning `RETRY` as the default value is a programming
 * error.
 */
export type ParseFunction<T> = (pick: PickFunction) => T | typeof NOT_FOUND;

function calculateDefault<T>(parse: ParseFunction<T>): T {
  return runWithPicks(alwaysPickDefault, (spanPicker) => {
    const pick = makePickFunction(spanPicker, 1);
    const val = parse(pick);
    if (val === NOT_FOUND) {
      throw new Error("parse function must return a default value");
    }
    return val;
  });
}

/**
 * A set of values that can be randomly picked from. Members are generated as
 * needed.
 */
export class Arbitrary<T> {
  readonly callback: ParseFunction<T>;

  /**
   * @param callback reads some picks and either returns a value or RETRY. It
   * should be deterministic and always finish.
   */
  constructor(callback: ParseFunction<T>) {
    this.callback = callback;
    calculateDefault(callback); // dry run; throws exception if invalid
  }

  /**
   * The default value of this Arbitrary. It's calculated by calling the
   * {@link callback} with default picks.
   */
  get default(): T {
    return calculateDefault(this.callback); // a clone, in case it's mutable
  }

  /**
   * Iterates over all solutions that can be generated by this Arbitrary.
   *
   * Uses a depth-first search, starting from the default value.
   */
  get solutions(): IterableIterator<Solution<T>> {
    const walk = (input: SpanPicker): T | typeof NOT_FOUND => {
      const pick = makePickFunction(input, 1);
      try {
        return pick(this);
      } catch (e) {
        if (e instanceof PickFailed) {
          return NOT_FOUND;
        } else {
          throw e;
        }
      }
    };
    return walkAllPaths(walk);
  }

  /**
   * Iterates over all values that can be generated by this Arbitrary.
   *
   * Uses a depth-first search, starting from the default value.
   */
  get members(): IterableIterator<T> {
    function* membersOf(arb: Arbitrary<T>): IterableIterator<T> {
      for (const s of arb.solutions) {
        yield s.val;
      }
    }
    return membersOf(this);
  }

  /**
   * Attempts to pick a value based on a prerecorded list of picks. All filters
   * must succeed the first time, or the parse fails. (There is no
   * backtracking.)
   *
   * This function can be used to test which picks the Arbitrary accepts as
   * input.
   */
  parse(picks: number[]): Success<T> | ParseFailure<T> {
    const input = new ParserInput(picks);
    return runWithPicks(input, (spanPicker) => {
      const pick = makePickFunction(spanPicker, 1);

      try {
        const val = pick(this);
        return input.finish(val);
      } catch (e) {
        if (e instanceof PickFailed) {
          return { ok: false, guess: this.default, errorOffset: input.offset };
        } else {
          throw e;
        }
      }
    });
  }

  /**
   * Creates a new arbitrary by mapping each member. (The default value is also
   * mapped.)
   */
  map<U>(convert: (val: T) => U): Arbitrary<U> {
    return new Arbitrary((pick) => {
      const output = pick(this);
      return convert(output);
    });
  }

  /**
   * Creates a new Arbitrary by removing members. (It must not filter out the
   * default value.)
   */
  filter(accept: (val: T) => boolean): Arbitrary<T> {
    if (!accept(this.default)) {
      throw new Error(
        "cannot filter out the default value of an Arbitrary",
      );
    }

    return new Arbitrary((it) => {
      const parsed = this.callback(it);
      if (parsed === NOT_FOUND) return NOT_FOUND;
      return accept(parsed) ? parsed : NOT_FOUND;
    });
  }

  /**
   * Creates a new Arbitrary by converting each member to another Arbitrary and
   * then picking from it.
   */
  chain<U>(
    convert: (val: T) => Arbitrary<U>,
  ): Arbitrary<U> {
    return new Arbitrary((pick) => {
      const output = pick(this);
      const next = convert(output);
      return pick(next);
    });
  }

  toString() {
    return `Arbitrary(default: ${this.default})`;
  }
}
