import {
  alwaysPickDefault,
  IntPicker,
  ParseFailure,
  ParserInput,
  PickRequest,
} from "../picks.ts";

import { FakePlayoutLogger, PlayoutLogger, Solution } from "../playouts.ts";
import { PlayoutFailed, walkAllPaths } from "../solver.ts";

import { Success } from "../results.ts";

export type PickFunctionOptions<T> = {
  /**
   * Filters out values that don't pass the given filter.
   *
   * @param accept a function that returns true if the picked value
   * should be accepted.
   *
   * It should always return true for an arbitrary's default value.
   */
  accept?: (val: T) => boolean;
};

/**
 * Picks a value given either a PickRequest or an Arbitrary.
 *
 * Throws {@link PlayoutFailed} if it couldn't find a value.
 */
export interface PickFunction {
  (req: PickRequest): number;
  <T>(req: Arbitrary<T>, opts?: PickFunctionOptions<T>): T;
}

/**
 * A function that generates a member of an Arbitrary, given some picks.
 *
 * The result should be deterministic, depending only on what `pick` returns.
 *
 * It may throw {@link PlayoutFailed} to indicate that a sequence of picks didn't
 * lead to a value.
 */
export type ArbitraryCallback<T> = (pick: PickFunction) => T;

export type PickMethodOptions<T> = {
  /**
   * How many times to retry filters. Set to 1 to disable backtracking.
   */
  maxTries?: number;

  log?: PlayoutLogger;
};

/**
 * A set of values that can be randomly picked from. Members are generated as
 * needed.
 */
export class Arbitrary<T> {
  readonly callback: ArbitraryCallback<T>;

  /**
   * @param callback reads some picks and either returns a value or RETRY. It
   * should be deterministic and always finish.
   */
  constructor(callback: ArbitraryCallback<T>) {
    this.callback = callback;
    this.default; // dry run
  }

  /**
   * Picks an arbitrary member, based on some picks.
   * @throws {@link PickFailed} when it calls `pick()` internally and it fails.
   */
  pick(input: IntPicker, opts?: PickMethodOptions<T>): T {
    const maxTries = opts?.maxTries ?? 1000;
    if (maxTries < 1 || !Number.isSafeInteger(maxTries)) {
      throw new Error("maxTries must be a positive integer");
    }

    const log = opts?.log ?? new FakePlayoutLogger();

    const callbackInput: PickFunction = <T>(
      req: PickRequest | Arbitrary<T>,
      opts?: PickFunctionOptions<T>,
    ): number | T => {
      if (req instanceof PickRequest) {
        return input.pick(req);
      }
      const accept = opts?.accept;

      // non-backtracking case
      if (accept === undefined) {
        const level = log.startSpan();
        const val = req.callback(callbackInput);
        log.endSpan(level);
        return val;
      }

      // retry when there's a filter
      for (let tries = 0; tries < maxTries; tries++) {
        const level = log.startSpan();
        const val = req.callback(callbackInput);
        if (accept === undefined || accept(val)) {
          log.endSpan(level);
          return val;
        }
        if (tries < maxTries - 1) {
          // Cancel only when we're not out of tries.
          log.cancelSpan();
        }
      }

      // Give up. This is normal when backtracking is turned off.
      // Don't cancel so that the picks used in the failed run are available
      // to the caller.
      throw new PlayoutFailed(
        `Failed to generate ${req} after ${maxTries} tries`,
      );
    };

    const val = this.callback(callbackInput);
    log.finished();
    return val;
  }

  /**
   * Attempts to pick a value based on a prerecorded list of picks. All filters
   * must succeed the first time, or the parse fails. (There is no
   * backtracking.)
   *
   * This function can be used to test which picks the Arbitrary accepts as
   * input.
   */
  parse(picks: number[]): Success<T> | ParseFailure<T> {
    const input = new ParserInput(picks);
    try {
      const val = this.pick(input, { maxTries: 1 });
      return input.finish(val);
    } catch (e) {
      if (e instanceof PlayoutFailed) {
        return { ok: false, guess: this.default, errorOffset: input.offset };
      } else {
        throw e;
      }
    }
  }

  /** The default value of this Arbitrary. */
  get default(): T {
    return this.pick(alwaysPickDefault, { maxTries: 1 }); // a clone, in case it's mutable
  }

  /**
   * Iterates over all solutions that can be generated by this Arbitrary.
   *
   * Uses a depth-first search, starting from the default value.
   */
  get solutions(): IterableIterator<Solution<T>> {
    return walkAllPaths((picker, log): T => {
      return this.pick(picker, { maxTries: 1, log });
    });
  }

  /**
   * Iterates over all values that can be generated by this Arbitrary.
   *
   * Uses a depth-first search, starting from the default value.
   */
  get members(): IterableIterator<T> {
    function* membersOf(arb: Arbitrary<T>): IterableIterator<T> {
      for (const s of arb.solutions) {
        yield s.val;
      }
    }
    return membersOf(this);
  }

  /**
   * Creates a new arbitrary by mapping each member. (The default value is also
   * mapped.)
   */
  map<U>(convert: (val: T) => U): Arbitrary<U> {
    return new Arbitrary((pick) => {
      const output = pick(this);
      return convert(output);
    });
  }

  /**
   * Creates a new Arbitrary by removing members. (It must not filter out the
   * default value.)
   */
  filter(accept: (val: T) => boolean): Arbitrary<T> {
    if (!accept(this.default)) {
      throw new Error(
        "cannot filter out the default value of an Arbitrary",
      );
    }
    return new Arbitrary((pick) => {
      return pick(this, { accept });
    });
  }

  /**
   * Creates a new Arbitrary by converting each member to another Arbitrary and
   * then picking from it.
   */
  chain<U>(
    convert: (val: T) => Arbitrary<U>,
  ): Arbitrary<U> {
    return new Arbitrary((pick) => {
      const output = pick(this);
      const next = convert(output);
      return pick(next);
    });
  }

  toString() {
    return `Arbitrary(default: ${this.default})`;
  }
}
