import { PickList } from "./picks.ts";
import { PickTree } from "./searches.ts";
import { PickFunction } from "./arbitrary_class.ts";
import Domain from "./domain_class.ts";

/**
 * Picks from the possible values generated by an Arbitrary, without
 * replacement.
 *
 * This can be used to generate permutations.
 */
export class Jar<T> {
  private readonly remaining = new PickTree();

  private acceptPicks = (picks: PickList) => this.remaining.prune(picks);

  constructor(readonly dom: Domain<T>) {}

  /**
   * Returns true if there are any values left that haven't been used.
   */
  isEmpty(): boolean {
    return this.remaining.done();
  }

  /**
   * Picks from an arbitrary with a filter that prevents it from using the same
   * pick sequence twice.
   *
   * @throws {@link Pruned} if the picks were used already.
   */
  pickUnused(pick: PickFunction): T {
    return pick(this.dom.generator, { acceptPicks: this.acceptPicks });
  }
}
